auto: true
server: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables","with_toc_data"]

# ------ Main Configs ------

title: webrtcjp.info
twittertag: webrtcjp
githuborg: webrtc-jp
ga: UA-61245362-1